### ISSUE TITLE
bug in poagraph.py

### ISSUE THREAD

**Issue by moold** [ljdursi/poapy#8]
Hi,  I am not sure whether it is an error on line 203 in poagraph.py.

 ```preds += [node_to_pn[inEdge.outNodeID] for _, inEdge in node.inEdges.items()]```

should be: 

  ```preds += [node_to_pn[inEdge.inNodeID] for _, inEdge in node.inEdges.items()]```

you can check line 31 and 70, 71 in poagraph.py.

**Comment by ljdursi** [comment]
Thanks for reporting.  I can’t take a look at this just yet but will shortly.

**Comment by ljdursi** [comment]
Good catch, I think you're right; in particular, that [line of code you referenced](https://github.com/ljdursi/poapy/blob/master/poagraph.py#L31) didn't enforce the ordering of nodes within an edge, which is assumed by the fix I made that created that line 203.  

I've updated the code in PR #9 - was there a particular case that led you to finding this you want to test out before I merge this?

**Comment by ljdursi** [comment]
I've merged #9; let me know if this fixes your problem.  Thanks again for reporting!

**Comment by moold** [comment]
No, I'm just learning the POA algorithm basing your nice code, and Thanks.
Btw, is the ```node.alignedTo``` necessary for POA?

**Comment by ljdursi** [comment]
It’s certainly part of the [original method](
https://academic.oup.com/bioinformatics/article/18/3/452/236691).  Imagine a bubble in the alignment, AAACCCAAA and AAAGGGAAA; without those aligned-to indicators it’s not clear if the bubble comes from deletion+insertion or mismatch-alignment.   Or AAACGCAAA AND AAAGGGAAA; without the aligned-to, you can’t tell if the middle G is a mismatch alignment or not.

There might be other ways to achieve that; for instance, maybe the nodes should be fully merged and have a list of bases (and their originating sequences) given.  That would certainly avoid the hoops I was jumping through (that you found the bug in) to fix the topological sort.  But since the point of this repo is to be a tutorial guide to the method I’m hesitant to stray too far from the paper.

**Comment by ljdursi** [comment]
I’m going to close this issue, since I think the bug has been fixed; feel free to re-open or open new issues for further comments or suggestions.
